# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0002_album_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='place_of_birth',
            field=models.CharField(default='SOME', max_length=250),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to='', verbose_name='Додати документ'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(default='', max_length=500, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=250, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='album',
            name='first_name',
            field=models.CharField(default='', max_length=250, verbose_name='Ім’я'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=100, verbose_name='Дата народження'),
        ),
    ]
