# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0004_auto_20161213_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='place_of_birth',
            field=models.TextField(default='', verbose_name='Місце народження'),
        ),
    ]
