# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0006_auto_20161213_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='address',
            field=models.TextField(default='', max_length=250, verbose_name='Адреса проживання'),
        ),
        migrations.AlterField(
            model_name='album',
            name='place_of_birth',
            field=models.TextField(default='', max_length=250, verbose_name='Місце народження'),
        ),
    ]
