# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0009_auto_20161214_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_of_birht',
            field=models.CharField(default='', max_length=100, verbose_name='Дата народження'),
        ),
    ]
