# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0011_auto_20161214_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='last_name',
        ),
    ]
