# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0012_auto_20161214_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Person'},
        ),
        migrations.AddField(
            model_name='album',
            name='house',
            field=models.CharField(default='', max_length=500, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='album',
            name='street',
            field=models.CharField(choices=[('Шевченка', 'Шевченка'), ('Садова', 'Садова'), ('Тургенівська', 'Тургенівська')], default='', max_length=500, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='album',
            name='address',
            field=models.TextField(default='', verbose_name='Місто проживання'),
        ),
    ]
