# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0013_auto_20161225_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='condition',
            field=models.CharField(choices=[('Реєстрація', 'Зняття з реєстрації')], default='', max_length=500, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='album',
            name='address',
            field=models.CharField(choices=[('м.Ірпінь', 'м.Ірпінь')], default='', max_length=250, verbose_name='Місто проживання'),
        ),
        migrations.AlterField(
            model_name='album',
            name='street',
            field=models.CharField(choices=[('вул.Шевченка', 'вул.Шевченка'), ('вул.Садова', 'вул.Садова'), ('вул.Тургенівська', 'вул.Тургенівська'), ('вул.Університетська', 'вул.Університетська')], default='', max_length=500, verbose_name='Вулиця'),
        ),
    ]
