# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0014_auto_20161230_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_doc',
            field=models.CharField(default='', max_length=250, verbose_name='Дата видачі'),
        ),
        migrations.AddField(
            model_name='album',
            name='number_doc',
            field=models.CharField(default='', max_length=250, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='album',
            name='subject_doc',
            field=models.CharField(default='', max_length=250, verbose_name='Суб’єкт, що видав'),
        ),
        migrations.AddField(
            model_name='album',
            name='type_doc',
            field=models.CharField(default='', max_length=250, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='album',
            name='whence_came',
            field=models.CharField(default='', max_length=250, verbose_name='Звідки прибув'),
        ),
        migrations.AlterField(
            model_name='album',
            name='condition',
            field=models.CharField(choices=[('Реєстрація', 'Реєстрація'), ('Зняття з реєстрації', 'Зняття з реєстрації')], default='', max_length=500, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_of_entry',
            field=models.CharField(default='', max_length=250, verbose_name='Дата реєстр./зняття'),
        ),
    ]
