# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0015_auto_20170116_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='seria_doc',
            field=models.CharField(default='', max_length=250, verbose_name='Серія документа'),
        ),
    ]
